### ISSUE TITLE
Add userInfo api

### ISSUE THREAD

**Issue by wood-crafter** [hoangph271/hbp#79]
userInfo must contant img and its infor

**Comment by wood-crafter** [comment]
> userInfo must contant img and its infor

And also, it should contant users that match or declined by this user

**Comment by hoangph271** [comment]
@wood-crafter 3nGlIsH

**Comment by hoangph271** [comment]
@wood-crafter sorry it takes too long...!
I'm working on a new route called `profiles`, which may return things like this:

```
username: string
title: string
avatarUrl: string
pictures: string[]
```

**Comment by hoangph271** [comment]
@wood-crafter I think we should work on these two problems first:
- Creating a `profile`
- Uploading avatar & pictures for a profile

**Comment by hoangph271** [comment]
@wood-crafter after that, we need to think about rules to get some random profiles
