### ISSUE TITLE
Add image api

### ISSUE THREAD

**Issue by wood-crafter** [hoangph271/hbp#80]
The api should response suggested image for each user (For now, it may return random images first)

**Comment by hoangph271** [comment]
@wood-crafter 
What do you mean by "suggested images"...?

Can you define it a little bit clearer:
- Why do you want these images...? What's the plan for them...?
- Should this be the `API`s just for just getting random images...?
Or should this be a module called `/partners?rule=nearby`
Should we define the `Partner` data model first...?

**Comment by hoangph271** [comment]
@wood-crafter random image here:

[https://alpha-sneu.xyz/api/v1/files/random/raw?mime=image/](https://alpha-sneu.xyz/api/v1/files/random/raw?mime=image/)

Or maybe checkout the Swagger UI

**Comment by hoangph271** [comment]
@wood-crafter use this endpoint for faster loading images:

[https://alpha-sneu.xyz/api/v1/files/random/raw?mime=image/&preview=true](https://alpha-sneu.xyz/api/v1/files/random/raw?mime=image/&preview=true)
